#!/usr/bin/env python3
"""
MoneyMath — General Image Generation Pipeline
Generates scene images using Gemini with an optional reference character image.

Usage:
  1. Set USE_REF_IMAGE = True/False depending on whether a character reference is needed
  2. If True, place your character reference image at reference/character.png
  3. Edit IMAGES below with your scene prompts
  4. Set PROJECT_NAME to your project folder name
  5. Run: python3 generate_images.py
"""

import os
import sys
import time
import base64
import concurrent.futures
from pathlib import Path
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
load_dotenv(ROOT / ".env")

from cost_tracker import log_gemini_image_cost

# ══════════════════════════════════════════════════════════
# API KEYS — Loaded from .env (more keys = faster parallel generation)
# ══════════════════════════════════════════════════════════

API_KEYS = [
    os.getenv("GEMINI_API_KEY"),
    os.getenv("GEMINI_KEY_1"),
    os.getenv("GEMINI_KEY_2"),
    os.getenv("GEMINI_KEY_3"),
    os.getenv("GEMINI_KEY_4"),
    os.getenv("GEMINI_KEY_5"),
    os.getenv("GEMINI_KEY_6"),
    os.getenv("GEMINI_KEY_7"),
    os.getenv("GEMINI_KEY_8"),
]
API_KEYS = [k for k in API_KEYS if k]
if not API_KEYS:
    print("ERROR: No GEMINI API keys found in .env")
    sys.exit(1)
print(f"Loaded {len(API_KEYS)} API keys")

# ══════════════════════════════════════════════════════════
# CONFIGURATION — Edit these for each new video
# ══════════════════════════════════════════════════════════

PROJECT_NAME = "invention-of-the-coin"  # Folder name under public/

MODEL = "gemini-3.1-flash-image-preview"

# Set to False to skip reference image (pure scene/documentary style)
USE_REF_IMAGE = True

# Reference character image — only loaded if USE_REF_IMAGE is True
REF_IMAGE_BYTES = None
REF_MIME = "image/png"
if USE_REF_IMAGE:
    REF_IMAGE_PATH = ROOT / "reference/character.png"
    REF_IMAGE_BYTES = REF_IMAGE_PATH.read_bytes()
    _ext = REF_IMAGE_PATH.suffix.lower()
    REF_MIME = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg", "webp": "image/webp"}.get(_ext.lstrip("."), "image/png")
    print(f"Loaded reference image: {REF_IMAGE_PATH} ({len(REF_IMAGE_BYTES) // 1024} KB)")
    print(f"Reference image type: {REF_MIME}")
else:
    print("Reference image: disabled (USE_REF_IMAGE = False)")

# Character base identity — face, skin tone, body type only. NO clothing.
# Each image prompt must specify scene-appropriate attire explicitly.
# The character MUST appear in every image — no objects-only shots.
# His position depends on the scene: examining a document, standing near a
# storefront, watching a crowd, etc. He is the visual focus for personal/
# emotional moments; background or peripheral for historical/data scenes.
CHAR = "The character from the reference image"

# Visual style constants
STYLE = "Cinematic documentary illustration, photorealistic detail, dramatic chiaroscuro lighting, rich warm colors, historically accurate, National Geographic quality."

# ══════════════════════════════════════════════════════════
# IMAGE PROMPTS — word-level precision: one image per narration sentence/phrase
# Each image illustrates the exact sentence being spoken at that moment.
# ══════════════════════════════════════════════════════════

IMAGES = [

    # ── HOOK (s1_hook) ──

    ("H01", "Aerial wide shot of the Pactolus River in ancient Lydia, western Turkey, at golden hour. The river winds through a valley with low hills in the background. The water catches sunlight, glinting gold from flecks of electrum in the riverbed. Ancient landscape, no modern structures, sparse trees along the banks. Cinematic, warm amber light, haze over the hills. Photorealistic documentary style."),
    ("H02", "Extreme close-up of a riverbed submerged in shallow clear water. Gold and silver flecks of electrum ore glint among dark river stones and fine sand. The camera angle is almost horizontal, skimming the surface. The light refracts through water onto the stones. Rich texture, hyperrealistic detail. No people, just the ore and the water."),
    ("H03", "Interior of an ancient Lydian metalworking workshop, circa 630 BCE. Stone walls, a clay forge glowing orange with coals. A craftsman wearing a simple linen tunic and leather apron stands at the forge, using iron tongs to hold a small crucible of molten electrum. Clay molds on the workbench beside him. Smoke rises toward a hole in the roof. The lighting is dramatic fire-orange. A Black man narrator figure in the background observes, dressed in period-appropriate Lydian linen tunic and sandals, watching the process with focused attention. Cinematic oil-painting quality."),
    ("H04", "Extreme close-up of an ancient Lydian electrum stater coin being struck by a bronze punch. The coin sits on a stone anvil. The punch is mid-strike, blurring with motion. The lion's head design on the obverse is visible, detailed and sharp. The background is a bokeh of the workshop. Hyperrealistic, dramatic side lighting from the forge fire."),
    ("H05", "Dramatic close-up of the face of an ancient Lydian electrum stater coin. The coin is slightly worn, greenish-gold patina. A detailed lion's head faces left, mouth slightly open, intricate mane lines visible. The surface gleams with high gold content. Background is black. Studio macro photography lighting, sharp detail on the high spots. Museum quality display lighting."),
    ("H06", "Scientific cross-section diagram rendered as a cinematic visual. A Lydian electrum stater coin sliced in half, showing the layered interior. The outer surface glows bright gold representing seventy three percent gold. The interior core is visibly less gold colored, more silver-gray representing fifty four percent gold. The background is dark slate. Scientific illustration meets documentary cinematography style."),

    # ── SETUP (s2_setup) ──

    ("S01", "Wide shot of an ancient Mesopotamian temple courtyard at dawn. Grain jars and clay amphorae are stacked in organized rows. Temple scribes in white linen robes record grain weights on clay tablets using reed styluses. A large scale with hanging pans dominates the foreground. Sunlight enters through high stone archways. Dust motes in the air. A Black man narrator figure in a linen robe stands near the scribes, observing the accounting process. Cinematic, warm light, ancient Near Eastern architecture. Documentary realism."),
    ("S02", "Close-up of a clay cuneiform tablet being inscribed with a reed stylus. The tablet is soft clay, the script pressed in deep clear wedge marks. A scribe's hands, close-up, wearing simple linen. The tablet records a grain debt. The background is a blurred storeroom with large clay vessels. Warm candlelight. Hyperrealistic, museum-quality texture on the clay."),
    ("S03", "A small outdoor market in ancient Lydia, circa 600 BCE. Stalls of woven fabric, dried fish, olives in clay pots, copper goods. Merchants and buyers in simple tunics haggling across the stalls. Two strangers completing a transaction, one placing a small electrum coin in the other's palm. Both examining the coin. A Black man narrator figure in a Lydian tunic watches from the edge of the market, hands clasped. Warm midday light. Cinematic wide shot. Historically accurate clothing and goods."),
    ("S04", "Close-up of a single Lydian electrum coin being placed into an open palm. The hand belongs to a Greek merchant in a simple chiton tunic. The coin glints in afternoon light. The background is softly blurred, a harbor with ships in the distance. The coin is small but perfectly struck. The moment of the first coin changing hands between strangers. Cinematic, warm Mediterranean light. Photorealistic."),

    # ── LYDIA (s3_lydia) ──

    ("L01", "Interior of the Lydian state mint, circa 620 BCE. A large workshop with multiple forge stations. Workers in leather aprons and linen tunics at various stages of coin production. One station melts electrum. Another pours into clay molds. A third strikes coins with bronze punches. A quality inspector examines finished coins under lamplight. Stone walls, clay floor, multiple hearths glowing. Cinematic wide shot showing the industrial scale of the operation. Smoke-filled, dramatic fire-orange lighting."),
    ("L02", "A Lydian mint worker using tongs to lower freshly struck electrum coins into a clay crucible containing a chemical solution, the depletion gilding process. The coins sizzle slightly in the liquid. The worker's face is illuminated by forge light, expression focused and skilled. Beside the crucible, finished coins gleam with enhanced gold surface. A Black man narrator figure observes closely from the side, dressed in Lydian linen tunic, expression thoughtful. Close-medium shot. Dramatic forge lighting."),
    ("L03", "Two electrum coins side by side on a dark stone surface. The left coin is natural electrum, slightly less bright. The right coin has been depletion gilded, its surface visibly more gold-colored. Both have the same lion's head stamp. Extreme close-up showing the textural and color difference between processed and unprocessed surfaces. Scientific documentary macro photography. Museum lighting, dark background."),
    ("L04", "The Lydian king's seal, a bronze punch in the shape of a lion's head, being pressed firmly onto a hot electrum coin blank. A craftsman's hands grip the punch with iron tongs, striking it with a stone hammer. The coin takes the impression. The lion's head is sharp, authoritative, detailed. The forge glows in the background. Extreme close-up of the moment of stamping. Cinematic, high contrast dramatic lighting."),
    ("L05", "A Lydian official in elaborate robes standing at a table of freshly minted electrum staters. He holds one up to oil lamp light, examining its golden surface with satisfaction. Behind him, stacks of coin pouches await distribution. His expression carries authority and confidence. The room is stone, with shelves of records and clay tablets. A Black man narrator figure stands in the doorway, dressed as a Lydian merchant, observing the official from a distance. Medium shot, warm lamp lighting, deep shadows."),
    ("L06", "Wide establishing shot of the ancient city of Sardis, Lydia, circa 600 BCE. A prosperous city at the foot of mountains. The royal palace on a hilltop, markets in the valley below, the Pactolus River winding through. Citizens in colored woolen tunics moving through market streets. The city feels wealthy, organized, powerful. Golden afternoon light. Painted in the style of a cinematic historical documentary. No modern elements."),

    # ── ATHENS (s4_athens) ──

    ("A01", "Wide shot of ancient Attic farmland at dawn. Rolling hills with terraced olive groves. A small stone farmhouse in the middle distance. In the foreground, a rectangular limestone horos stone stands upright in the soil at the edge of the field, a mortgage marker, plain and official. A farmer in a simple short chiton stands near it, head slightly bowed, looking at it. The early morning light is cool and blue-gray, just turning golden. Sparse, austere, emotionally weighted. Cinematic wide shot."),
    ("A02", "Close-up of an ancient Greek horos stone, a rectangular slab of rough limestone with carved Greek letters. The stone is weathered, set into soil. The inscription indicates a debt claim on the land. Moss at the edges. The stone casts a long shadow in low morning light. Behind it, blurred rows of olive trees. Museum-quality realism. Documentary photography style."),
    ("A03", "Interior of a small ancient Athenian home. A creditor in a fine wool himation stands across a low table from a farmer and his family. The creditor holds an inscribed debt tablet. The farmer, in worn linen, stands with his wife and two children. The farmer's expression is strained, resigned. The children are small. Oil lamp light illuminates the scene. The room is spare. A Black man narrator figure stands in the shadows near the doorway, dressed in period Athenian chiton, observing with gravity. Cinematic medium shot."),
    ("A04", "An ancient Greek harbor scene. A wooden ship at the dock. Chains link a group of men and women in worn tunics, Athenian debt slaves being loaded onto the ship. Guards in armor oversee the boarding. Families watching from the dock, some reaching out. The sea is flat, gray. The atmosphere is somber and heavy. No heroism, no spectacle, just the terrible bureaucratic fact of the moment. Cinematic wide shot. Documentary-weight historical realism."),
    ("A05", "Solon, an older Greek man with a white beard, wearing a formal himation draped over his shoulder, standing in the Athenian agora addressing a gathered crowd. He gestures with authority. The crowd is mixed, merchants, farmers, wealthy men in fine tunics, laborers in rough cloth. The columns of the stoa visible behind him. Morning light. The crowd's faces carry a mix of hope and tension. A Black man narrator figure stands at the edge of the crowd, dressed in Athenian citizen's chiton, listening. Cinematic wide shot."),
    ("A06", "Workers in the Attic countryside pulling a horos stone from a field. Two men lever it up with wooden poles while a third pulls. The stone is coming free of the earth, soil clinging to its base. Farmers in the background watching. The sky is overcast but bright. The mood is cautiously hopeful. The physical act of removing a debt marker from land. Cinematic medium shot, morning light, historical clothing, short linen chitons, leather sandals."),
    ("A07", "Ancient Greek parchment or papyrus with a poem written in archaic Greek script. The text is Solon's poem about the black earth being freed. The document is lit from the side, casting gentle shadows. A hand reaches in to point at a specific line. The background is a dark wooden table in a library setting with scroll cases visible. Close medium shot, warm golden light."),
    ("A08", "Solon walking alone through an ancient harbor city, perhaps Alexandria or a Cypriot port, in voluntary exile, dressed simply in traveling clothes, a rolled scroll under his arm. He looks out at the sea. The city behind him is active, foreign, bustling. He is older, white-bearded, thoughtful. The light is Mediterranean afternoon, bright and hot. A solitary figure against a large world. Cinematic portrait shot."),

    # ── ALEXANDER (s5_alexander) ──

    ("AL01", "The burning of Persepolis. The great palace complex lit from within by enormous fires at night. Columns still standing, silhouetted against an orange sky. Smoke rising in vast columns. Alexander the Great in Macedonian military dress, bronze cuirass, red cloak, crested helmet, stands in the foreground on a stone terrace watching. Sparks and embers drift through the air. Cinematic wide shot, historically accurate Achaemenid architecture in the background."),
    ("AL02", "Inside the Persian treasury at Persepolis. A vast vaulted stone room packed floor to ceiling with stacked silver and gold. Chests open to reveal ingots. Clay jars of coin. Piles of bullion. Torchlight reflects off surfaces in every direction, the room glowing with metallic light. Persian treasury guards in elaborate robes and armor, now in shock, standing back as Macedonian soldiers survey the hoard. A Black man narrator figure, dressed as a Macedonian soldier attendant, stands in the background taking in the scale of the room. Cinematic wide shot."),
    ("AL03", "A massive caravan crossing a mountain pass at dawn. Hundreds of camels and mules loaded with wooden chests and sealed clay jars, stretching back into the mountain mist as far as the eye can see. Macedonian soldiers escort the caravan, spears at the ready, in bronze armor. The scale is overwhelming, the logistics of moving an empire's wealth. Cinematic wide shot, low morning light, dramatic mountain landscape."),
    ("AL04", "A Hellenistic mint operating at industrial capacity. A large stone building with multiple forge stations working simultaneously. Workers in tunics striking coins, pouring silver, managing molds. Supervisors walk the floor. A cart of silver ingots is being unloaded at the entrance. The coins being struck are Alexander tetradrachms. A Black man narrator figure in attendant clothing watches from a mezzanine above. Wide shot, multiple fires, smoke and light."),
    ("AL05", "A West African coastal market in the mid-sixteen hundreds. Merchants at stalls selling cloth, spice, grain, pottery. Cowrie shells used as currency, visible in piles and pouches. Portuguese traders arrive carrying large bags and begin to pour cowrie shells onto the market ground, far more than the market has ever seen at once. The local merchants look confused, then alarmed. The shells keep coming. Wide shot, tropical coastal setting, bright equatorial light, diverse period-appropriate West African and Portuguese clothing."),
    ("AL06", "A West African market stall, close up. A merchant holds a price board where numbers are written. She is changing them, erasing the old numbers and writing higher ones. Her expression is grim and resigned. Behind her, the piles of cowrie shells from the Portuguese traders are visible. The purchasing power of her savings has just dropped. The trade that used to sustain her is being disrupted. Medium shot, warm afternoon light, West African coastal setting, sixteenth century."),

    # ── ROME (s6_rome) ──

    ("R01", "A Roman soldier in the late first century CE receiving his pay. A legionnaire in full armor, lorica segmentata, red tunic, sandals, holds out his hand as a paymaster places a stack of bright silver denarii into his palm. The coins are pristine, high silver content, gleaming. The paymaster is at a wooden pay table in a Roman military camp. The coins catch the light. Pride and satisfaction on the soldier's face. Medium shot, midday light in a Roman castra setting."),
    ("R02", "A timeline display rendered cinematically. Four Roman denarii coins arranged left to right, each from a different era. The first, under Augustus, is bright silver and perfectly struck. The second, under Nero, is slightly less silver. The third, under Septimius Severus, is noticeably more gray, less silver. The fourth, from the late third century, is bronze with only a faint silver wash, partly rubbed away. The coins sit on dark stone. The change is visible and devastating. Museum macro photography, studio lighting, dark background."),
    ("R03", "A Roman bread market in a provincial town, late second century CE. A baker in a simple tunic behind a stall of round loaves. A price board behind him written on a whitened wall. Customers in the market queue. A Black man narrator figure dressed as a Roman townsman in tunic and sandals stands at the stall, studying the prices. The scene is ordinary but the prices are the point. Cinematic medium shot, morning Mediterranean light."),
    ("R04", "The same Roman bread market stall, a generation later, the late third century. The baker is different but the stall is similar. The prices on the board behind him are dramatically higher. The queue of customers is longer, more ragged. The coins they carry look different, smaller, duller. The Black man narrator figure, now in slightly more worn clothing, watches from the same position. The visual comparison between this and the previous image tells the story of inflation. Cinematic medium shot."),
    ("R05", "A Roman legionnaire kneeling before a Roman emperor in a grand stone hall. The soldier's armor is worn, his expression exhausted and imploring. He gestures to show the coins in his hand, not many. The emperor, seated on a raised throne in purple robes, watches from above with bureaucratic detachment. An attendant nearby prepares to hand over a new coin pouch. The soldier does not know the new coins are worth even less. Cinematic wide shot, Roman imperial interior, columns and marble, torchlight."),
    ("R06", "Extreme close-up of a late Roman antoninianus coin. The surface shows a silver wash that is visibly wearing through in spots, revealing the bronze beneath. The coin's face is worn. The emperor's portrait on the obverse is still legible. The silver coating chips along the rim. Hyperrealistic macro photography, raking side light to reveal the texture. Dark background. The physical evidence of debasement made visible."),
    ("R07", "A map of the Roman Empire during the Crisis of the Third Century, rendered as a cinematic visual. Fracture lines appear across the territory. Small markers indicate the rapid succession of emperors, each one appearing and disappearing quickly. Trade routes dim. The borders thin. The map communicates collapse through visual fragmentation. Dark background, gold and red color palette, cinematic documentary style."),

    # ── MODERN (s7_modern) ──

    ("M01", "Cerro Rico, the Potosi silver mountain in Bolivia, in the colonial era. The distinctive cone-shaped peak rises against a high-altitude blue sky. At its base, the colonial city of Potosi spreads out, populated and busy. The mountain itself shows excavation marks and mining activity from the sixteenth century. The scene is vast and slightly ominous, this mountain changed the world. Wide establishing shot, cold high-altitude light, dramatic clouds."),
    ("M02", "Interior of the colonial Potosi mint, mid-sixteen hundreds. Indigenous workers in rough cloth operate coin-striking machinery by hand and foot. Spanish overseers in doublets and boots supervise. Silver ingots arrive from carts. The work is hard, mechanized by the era's standards, continuous. The building is stone, industrial for its era. A Black man narrator figure, dressed in the clothing of a colonial-era observer in dark coat and wide-brimmed hat, watches from a shadowed corner, expression grave. Wide shot, daylight through high windows, dust."),
    ("M03", "The dollar sign rendered as a graphic overlay beside the historical Potosi mint mark, the stylized PTSI lettering superimposed on a column. Both symbols sit on a dark background, side by side, connected by a visual line. The design is cinematic and educational. The visual makes the historical connection legible. Crisp, modern documentary graphic design aesthetic."),
    ("M04", "Interior of a modern currency printing facility. A long industrial machine prints sheets of one hundred dollar bills. Workers in blue uniforms monitor the process from elevated walkways. The bills are crisp, green, identical. The scale is enormous. The room is clean and highly technical. Cinematic wide shot, fluorescent lighting, the industrial production of trust."),
    ("M05", "Close-up of a college student's desk, late at night. A laptop screen shows an online student loan portal with a balance and an interest calculation. Papers, textbooks, coffee cup. A young Black man in casual clothes looks at the screen with a resigned but focused expression. The numbers are high. The room is a small apartment. Warm lamp light, the blue glow of the screen. Cinematic close medium shot."),
    ("M06", "A graduation ceremony viewed from above. Rows of students in black caps and gowns receive their diplomas. The aerial shot is wide, the students are tiny, the rows are perfectly organized. It looks like triumph. But the visual framing is slightly cold and bureaucratic, the rows look like a ledger. Cinematic drone shot perspective, bright afternoon light, green lawn."),
    ("M07", "Close-up of several modern coins in a hand, American quarters and dimes, clearly showing the milled ridges along the edges. The camera angle is low, showing the ridges in sharp relief. The light rakes across the coin edge from the side to make the ridges dramatically visible. A simple, clear close-up that draws attention to something people see every day but never notice. Hyperrealistic macro photography, neutral background."),
    ("M08", "A portrait of Isaac Newton in his role as Master of the Mint, circa 1700. He sits at a desk in the Royal Mint building, dressed in a dark coat with white cravat, period clothing of the English late seventeenth century. On the desk before him: a collection of coins, some clipped at the edges, the crime he was combating, and beside them, newly minted coins with perfect milled edges. He holds one up, examining it. Expression sharp and analytical. Candlelight, dark wood interior, serious documentary tone."),
    ("M09", "A person tapping a contactless payment card on a modern payment terminal at a shop counter. The terminal screen shows a transaction confirmation. The hand is relaxed and casual, this is a routine moment. The shop is modern, urban, the background softly blurred. The image is ordinary on purpose, a contrast to the ancient world shown throughout the video. The coin is gone. The transaction continues. Clean, bright, commercial lighting."),

    # ── CLOSING (s8_closing) ──

    ("C01", "Return to the Pactolus River, now at golden hour. The same winding river from the opening, but the light is warmer, more resolved. The water still glints with electrum flecks. The landscape is peaceful but carries the weight of the full story. Wide shot, no people, just the river and the hills and the fading light. Cinematic, contemplative, full circle."),
    ("C02", "A museum case displaying the world's first Lydian electrum stater coin. The case is glass, well-lit, the coin centered on a velvet platform. The coin is small, green-gold with age. The museum card beside it reads the name in formal text. A Black man narrator figure in modern casual clothing, dark jacket, no tie, stands before the case, hands clasped behind him, looking at the coin in silence. The camera is slightly behind him, the coin and his reflected face visible through the glass. Cinematic medium shot, museum ambient lighting."),
    ("C03", "Split composition: on the left, the ancient Lydian electrum stater with its lion's head. On the right, a modern touchless payment terminal screen showing a transaction approved. The two images are visually rhymed, the lion's head and the bank logo occupy the same position in the frame. No text. The visual connection is the entire argument. Studio lighting, dark background, cinematic graphic composition."),
    ("C04", "A vast museum vault filled with coins from every era. Cases upon cases of coins: Greek, Roman, Byzantine, Ottoman, colonial Spanish, nineteenth century, modern. A Black man narrator figure in a dark modern jacket walks slowly through the center aisle, hands behind his back, looking from case to case. The camera follows at a distance. The room is large and quiet, lit with warm track lighting on each case. Every coin is a different answer to the same question. Cinematic tracking shot, wide and deep."),
    ("C05", "Final image: The Pactolus River at dusk, just the water and the last light. The water is dark now, the gold flecks barely visible, but there. No people. No sound implied. The landscape that started everything, unchanged after three thousand years. Cinematic, wide, quiet. The last image of the video. A sense of immense, patient time."),

    # ── HOOK additional ──
    ("H07", "The Lydian king on a raised throne in a columned audience hall, receiving the first bag of newly minted coins from his chief mint official. The king's expression is satisfied and strategic. The official bows presenting the coin pouch. Torchlight on gold and stone walls. Wide shot, historically accurate Lydian royal court clothing — elaborate patterned wool robes, gold neck ornaments. Cinematic."),
    ("H08", "A traveling merchant on a dusty road between ancient cities, pausing to examine a small electrum coin in his palm. His pack donkey is loaded behind him. The road stretches through dry hills. He holds the coin up to the afternoon sun, squinting at its surface. His tunic is worn, practical. The road is ancient and unpaved. Cinematic medium shot, golden late afternoon light."),
    ("H09", "Two ancient Lydian merchants completing a trade transaction at a market stall — one handing over a small pouch of electrum coins, the other counting them on a cloth. Both in Lydian linen tunics and leather sandals. The stall sells ceramic jars and textiles. Both faces intent on the transaction. Cinematic medium shot, market background busy and colorful."),
    ("H10", "Wide night shot of the ancient city of Sardis from a distance, city lights visible as scattered oil lamp fires through windows and doorways, the royal palace lit on the hilltop, the Pactolus River a dark ribbon below. A quiet, slightly ominous city at night, the first city in human history to issue standardized metal currency. Cinematic, atmospheric."),

    # ── SETUP additional ──
    ("S05", "An ancient Lydian market scene showing the awkward pre-coin problem: a farmer with a cart of grain trying to acquire a bronze knife from a smith. The smith shakes his head, not needing grain. Both men frustrated. Barter transaction failing. Cinematic medium shot, outdoor market, warm midday light, period-appropriate clothing."),
    ("S06", "Interior of an ancient temple storage room in Mesopotamia circa 3000 BCE. Rows of large clay storage jars labeled in cuneiform. A priest-administrator in white robes reviews accounts by oil lamp. The system is organized but completely dependent on physical proximity. A Black man narrator figure in period robes observes from behind the priest. Warm amber light, ancient architecture."),
    ("S07", "A camel caravan crossing a mountain pass, the traders carrying goods but no standardized currency. Two lead merchants negotiate with gestures over a pile of mixed commodities on a blanket. The problem of value exchange without a shared standard is visible in their frustrated expressions. Cinematic wide shot, dramatic mountain landscape, sunset."),
    ("S08", "A Greek harbor scene showing the moment coins began replacing barter. A merchant holds up an Athenian silver owl coin — the first coins he has seen — while a Lydian trader explains its worth. Both men in period tunics. Ships in the harbor behind them. The coin changes hands between people who share no language except the stamp's authority. Mediterranean morning light. Cinematic."),
    ("S09", "Close-up of a leather pouch being opened to reveal a small pile of early Greek silver coins — owl coins and Lydian electrum staters mixed. A merchant's calloused hand sorts them. The coins represent the new portability of value. Background: a dockside scene. Warm Mediterranean afternoon light. Hyperrealistic macro detail on the coins."),
    ("S10", "An ancient agora in early Greece. Merchants from different city-states completing trades using coins from their respective cities. A money-changer at a small table evaluates coins from various sources, weighing them on a balance scale. The problem of multiple coin standards is already emerging. A Black man narrator figure in Athenian chiton watches the money-changer work. Cinematic wide shot, morning light, columns in background."),
    ("S11", "The same ancient agora, close-up of the money-changer's balance scale. On one pan, an Athenian silver owl. On the other, a Lydian electrum stater. The scale is slightly off-balance. The money-changer has a stylus and tablet recording the exchange rate. This is the moment the complexity of monetary systems begins. Cinematic close-up, dramatic side lighting."),
    ("S12", "A Black man narrator figure in a modern dark jacket standing in front of a projected ancient map showing the spread of coin use from Lydia across the Mediterranean world, arrows indicating the direction of coin adoption. He gestures at the map. Modern documentary presentation style. Dark background, the map is the main light source. Bridge between ancient and present."),
    ("S13", "A clay counting table in an ancient Lydian merchant's office, circa 580 BCE. Rows of small electrum coins sorted by denomination. Wax tablets with accounts beside them. A leather ledger open. The merchant's hands count the coins. The coin has created a new kind of calculation. Close-up of hands and coins, warm lamp light, stone workspace."),
    ("S14", "Abstract documentary graphic: two systems side by side. Left: a diagram of the old relationship-credit system showing arrows between temple, farmer, laborer, connected by personal ties and social memory. Right: the coin system — a single coin at the center, radiating out to strangers who have never met, connected only through the stamp. Clean, dark background, cinematic graphic style."),

    # ── LYDIA additional ──
    ("L07", "A close-up of a modern scientist using an XRF analyzer (X-ray fluorescence spectrometer) to analyze an ancient Lydian electrum stater coin in a laboratory setting. The coin sits under the analyzer's sensor. Computer screen in the background shows elemental analysis data. The scientist wears latex gloves. Clean modern laboratory, the ancient coin on the modern instrument. Documentary realism."),
    ("L08", "Computer screen showing XRF spectroscopy results for the Lydian electrum stater. Two data columns: SURFACE: 73 percent gold. CORE: 54 percent gold. Bar graphs showing the difference in gold content. Scientific data visualized clearly. The contrast between surface and core is the entire argument. Clean infographic style on dark monitor background."),
    ("L09", "A Lydian metallurgist circa 620 BCE, crouching beside a stone trough containing the depletion gilding solution, carefully lowering freshly cast coin blanks into the liquid using iron tongs. His expression is concentrated, technical. The solution fumes slightly. Torchlight reflects in the liquid. His leather apron and linen clothes are marked with work. Cinematic close-medium shot."),
    ("L10", "Extreme close-up of a freshly depletion-gilded Lydian coin being lifted from the solution on iron tongs. The surface is now distinctly more golden than the underside of the tongs. Water drops fall from the coin as it emerges. The golden surface glints in forge-fire light. The deception is chemically complete. Hyperrealistic macro, dramatic orange light."),
    ("L11", "Ancient Lydian coin workshop: the quality control station. An older supervisor holds a finished electrum stater against an oil lamp, rotating it to inspect the surface gold quality. Beside him, a pile of approved coins and a smaller pile of rejected ones. His expression is critical, expert. He is judging the surface appearance, not the interior content. Cinematic medium shot, warm lamp light."),
    ("L12", "The ancient site of Sardis today — an archaeological excavation in western Turkey. The Pactolus River visible in the background. Archaeologists in modern khakis work at trench edges. Wooden signs mark the ancient mint location. The site is arid, the mountains behind. Cinematic documentary photography, afternoon light, the real place where it all started."),
    ("L13", "A portrait of the historian Sture Bolin, imagined in a mid-century academic office circa 1958. He sits at a desk covered in coin photographs and reference books, writing his study of ancient coinage. His expression is focused, slightly troubled. Behind him, a glass case of ancient coins on a shelf. He is writing the words that will call the first coins the first numismatic deception. Candlelight-style warm tones in a dark paneled academic office."),
    ("L14", "A simplified diagram shown as a documentary visual: the Lydian mint's operation illustrated in three steps. Step 1: electrum from river (73 percent gold). Step 2: deliberate alloying lowers to 54 percent gold. Step 3: depletion gilding restores surface to 73 percent gold. Three side-by-side illustrations, clean educational style, dark background, documentary visual design."),
    ("L15", "The lion-head die for the Lydian electrum stater, a bronze punch with the lion's face carved in intaglio, sitting on a stone workbench beside a completed coin showing the positive impression. The detail of the lion's mane is intricate and authoritative. Oil lamp light from the side illuminates the die and coin in warm gold. Documentary macro photography on dark stone surface."),
    ("L16", "A Lydian merchant in the marketplace testing a coin by biting it — the standard test for silver purity. His teeth find a hard surface. The coin looks and bites like quality metal. He accepts it. He cannot know the core is diluted. The fraud is complete at the point of transaction. Cinematic close-medium shot, busy market background, warm midday light."),
    ("L17", "A wide shot of ancient trade routes emanating from Lydia across the Mediterranean world, shown as an animated documentary map. The Lydian electrum stater spreads along trade routes to Greek cities, to Egypt, to Persia. The map shows how quickly the coin concept spread — within decades — once Lydia introduced it. Gold lines representing coin trade routes radiating outward from Sardis. Dark background, cinematic documentary style."),
    ("L18", "A split image: left side shows the original Pactolus River electrum (natural gold-silver alloy, 73 percent gold) as a geological sample — raw, unprocessed, naturally occurring. Right side shows the minted Lydian electrum stater — processed, enriched surface, stamped, the natural material converted into a state-certified number. The transformation from nature to currency, side by side. Studio lighting, dark background."),
    ("L19", "The first generation of Lydian coins being loaded into leather pouches and distributed to merchants by royal palace officials. A line of merchants in colorful tunics receive the pouches, examining the coins, some biting them or holding them to the light. A palace scribe records each distribution. The Lydian royal palace courtyard in afternoon light. Cinematic wide shot."),
    ("L20", "Aristotle in his Athens study circa 340 BCE, holding a small coin in one hand and writing in a notebook with the other. He is writing his analysis of money as a social convention in the Politics. His expression is thoughtful, analytical. Scrolls and manuscripts around him. A small oil lamp illuminates his work. His face shows the intellectual pleasure of a concept becoming clear. Classical Greek interior, warm lamp light."),
    ("L21", "A Greek trading ship at sea, mid-Mediterranean, circa 550 BCE. Sailors in simple tunics work the rigging. In a locked chest on the deck, the captain's trade coins — Lydian electrum staters and early Athenian owls — rattle as the ship rises and falls. Close-up of the chest slightly ajar, coins visible inside. The coin is now traveling across the ancient world. Cinematic, sea light, blue Mediterranean."),
    ("L22", "A Black man narrator figure, dressed as a Lydian citizen in simple linen tunic and sandals, standing in the Sardis marketplace and holding a single electrum stater up to the camera. His expression is steady, knowing. He turns the coin slightly so the lion's head faces the viewer. The marketplace is blurred behind him. He is showing you the beginning of everything. Cinematic medium portrait, warm market light."),

    # ── ATHENS additional ──
    ("A09", "Close-up of an Athenian farmer's hands, weathered and calloused, holding a small number of silver coins — clearly not enough. His expression is one of quiet desperation. The coins are bright Athenian owls, the debt he owes is more than he holds. Background: the entrance to a creditor's home, stone steps, closed door. Cinematic close-medium shot, afternoon light."),
    ("A10", "An ancient Athenian creditor's office, circa 600 BCE. A wealthy man in a fine wool himation sits behind a table with rows of clay tablets recording debts. A nervous farmer in worn linen stands before him, explaining his situation. A clerk records new terms. The power differential is visible in posture, clothing, and the arrangement of furniture. Cinematic medium shot, warm lamp light."),
    ("A11", "Ancient Attic olive fields in late autumn. Most of the harvest has been picked. A farmer surveys what remains — not enough to repay the debt. In the background, a horos stone is visible at the field's edge. He is calculating the math of his situation. His expression carries the exhaustion of someone who has done this math before and knows the answer. Cinematic wide shot, cool autumn light."),
    ("A12", "A debt collection scene in ancient Athens, circa 590 BCE. A creditor and two officials arrive at a small farm at dawn. The farmer's family watches from the doorway as the officials place a new horos stone at the field boundary. The farmer stands with his arms at his sides, unable to stop them legally. The child in the doorway watches. Cinematic wide shot, cold dawn light, emotionally heavy."),
    ("A13", "An Athenian law court, circa 600 BCE. A stone hall with rows of seated citizen-judges. A creditor stands at the speaker's position with a debt tablet, making the legal case for seizing a farmer's land and family. The accused farmer stands to the side, in worn clothing, no advocate. The legal machinery of coin-denominated debt at work. Cinematic wide shot, bright midday light through open roof."),
    ("A14", "The moment of debt enslavement in ancient Athens. An official places chains on an Athenian farmer's wrists, watched by his creditor, in front of the farmer's home. His wife turns away. Two children hold each other. The creditor is not cruel — he is businesslike. This is what the law requires. Cinematic medium wide shot, gray afternoon light, emotionally devastating without being exploitative."),
    ("A15", "A Lydian-style slave market in a Greek city, circa 590 BCE. Athenian debt slaves being offered for sale alongside foreign slaves. Some are clearly from farming families — their hands and clothing suggest agricultural work. A wealthy buyer examines one of them. The mechanism has moved a person from farmer to commodity in a single harvest cycle. Cinematic wide shot, market setting, heavy atmosphere."),
    ("A16", "Solon in his study at night, circa 595 BCE, reading debt petitions by oil lamp. Parchment scrolls piled before him. He is reading the scale of the problem. His face shows the weight of what he is about to be asked to do. An old man with a white beard, in simple Athenian clothing. The lamplight catches his eyes. A man preparing to make a decision that will shake Athens. Cinematic close-medium portrait."),
    ("A17", "The Athenian Assembly in session, circa 594 BCE, voting to appoint Solon as archon with emergency powers. Citizens raising their hands. The acropolis visible in the background beyond the assembly columns. The vote carries. A historic moment, unrecognized as historic by most of those present. Cinematic wide shot, morning light, crowded assembly of Greek citizens in various tunics."),
    ("A18", "The seisachtheia in action: workers physically breaking clay debt tablets on the steps of the Athenian agora, by official order. The tablets crack and shatter on the stone steps. A crowd of farmers watches, some with hands over their mouths, some crying. Creditors in fine clothes stand apart, watching in visible anger. Solon observes from a raised position. Cinematic wide shot, complex emotional atmosphere."),
    ("A19", "Close-up of a horos stone being split in half with an iron tool in an Attic field. The stone cracks cleanly. The debt inscription is now two pieces, unreadable. A farmer's boot stands beside it. The soil is visible at the base where the stone was embedded for years. The moment of debt cancellation made physical. Cinematic close-up, morning light, earth tones."),
    ("A20", "A freed Athenian debt slave walking out of a foreign port city — Alexandria or a Black Sea port — toward a waiting ship. He is carrying almost nothing. His clothing is worn. But he is walking freely. Behind him, the foreign city. Ahead, a ship that will take him home. The moment after the seisachtheia reached across the Mediterranean. Cinematic wide shot, evening harbor light."),
    ("A21", "Solon writing the poem about the black earth being freed, at his desk in Athens, the morning after the seisachtheia. He writes by lamplight. The poem is taking shape on papyrus. Outside his window, the city is quiet and stunned. His face carries the exhaustion of a man who has just done something necessary and irreversible. Cinematic close-medium shot."),
    ("A22", "Solon's ship departing from Piraeus harbor, Athens. He stands at the prow, looking back at the city receding behind him. He is beginning his ten-year voluntary exile. The city he transformed is still visible on the hill. The Acropolis, the agora, the fields he freed. He is leaving so the laws can stand. Cinematic wide shot, dawn harbor light."),
    ("A23", "A wealthy Athenian creditor's household, circa 584 BCE — four years after the seisachtheia. New loan documents are being drawn up at a table. New silver coins on the table. A new borrower, another farmer in worn clothes. The horos stones are being prepared again. The system has returned, as Solon knew it would. Cinematic medium shot, warm lamp light, quiet dread."),
    ("A24", "An Attic field with a new horos stone — fresh limestone, recently carved — standing at the field's edge. The carving is sharp, unweathered. Beside it, the faint outline in the soil where an older stone was removed a few years ago by Solon's seisachtheia. The system's return, documented in stone. Cinematic wide shot, morning light, emotionally heavy."),
    ("A25", "A Black man narrator figure in modern dark clothing standing in the ruins of the ancient Athenian agora. Behind him, visible column stumps and the archaeological foundation of the stoa. He holds a small replica horos stone in one hand, looking at it. He places it back on the ground carefully. The ancient system visible as ruins around him. Cinematic medium shot, afternoon sun on stone."),
    ("A26", "Documentary graphic comparing two systems side by side: left panel shows pre-coin Athenian farming debt — amount owed in grain, tracked by social relationship, flexible with harvest. Right panel shows coin-denominated Athenian debt — amount in silver, specific date, legally enforceable, grows regardless of harvest. The structural difference that changed everything. Clean documentary graphic style, dark background."),
    ("A27", "A wide shot of Athens as it would have appeared circa 590 BCE, before the seisachtheia. The city is prosperous in parts — the acropolis rising, the agora busy — but in the countryside, horos stones dot every other field. The stones are visible even from this distance. They are everywhere. Cinematic aerial historical illustration, morning light, painted in documentary style."),
    ("A28", "A Greek silver owl coin — the Athenian tetradrachm — held up against the light, showing the owl and olive branch on the reverse. The coin is the standard currency of Athens, the one used in the hektemoroi debt contracts. Beautifully struck, full of civic pride. And at the same time, the instrument of the debt trap. Macro photography, museum lighting, dark background."),
    ("A29", "Solon, years later, at a foreign city — perhaps Egypt — sitting with a local scholar, discussing law. An older man now, in simple traveling clothes. He is describing what he did in Athens. The foreign scholar listens with great interest. Solon is not famous yet; he is just a traveler with a remarkable story. Cinematic medium shot, Mediterranean afternoon light."),
    ("A30", "The Athens of 580 BCE — ten years after Solon, six years into his exile. The city is stable, the debt system rebuilt but more legally constrained than before. The agora is busy. The horos stones are back in some fields. A new generation of farmers is borrowing. The system returned, exactly as the structure demanded. Cinematic wide establishing shot, documentary historical illustration."),

    # ── ALEXANDER additional ──
    ("AL07", "Alexander the Great, in full Macedonian military dress — bronze cuirass, red cloak, Corinthian helmet raised to show his face — surveying a map of the Persian Empire spread on a campaign table. He plans not just conquest but monetization. His generals stand around him. The tent is lit by oil lamps, the map is large. Cinematic wide shot, military command atmosphere."),
    ("AL08", "The moment Alexander enters Persepolis for the first time. Wide shot of the great gate and columns, Alexander's forces filing through. The city is immense. Alexander on horseback in the foreground is dwarfed by the scale of Achaemenid architecture. He has just arrived at the largest treasury in the ancient world. Cinematic wide shot, dramatic lighting."),
    ("AL09", "The Persian treasury of Persepolis being inventoried by Macedonian officials. Scribes with clay tablets moving through the chamber, recording what they find. Silver ingots stacked in rows taller than a man. Chests of gold. Persian accounting records that no one has touched in decades, now being catalogued by the conquerors. Cinematic wide shot, torchlight, vast scale."),
    ("AL10", "Macedonian soldiers loading silver ingots onto the backs of camels, outside the Persepolis treasury gates. The camels kneel, the silver is loaded in wooden frames. A line of animals stretching into the distance. The logistics of moving 200,000 talents of bullion made physical. Cinematic wide shot, dust, afternoon heat."),
    ("AL11", "Alexander's traveling mints in the field — portable forge stations following the army, striking coins from the Persian bullion as the campaign advances. Workers in military-adjacent clothing strike tetradrachms with Alexander's portrait on the obverse. The coins come out fast, in volume. A Black man narrator figure dressed as a Greek attendant watches the operation. Cinematic medium shot, forge fire, military camp setting."),
    ("AL12", "A Greek marketplace in Egypt, circa 330 BCE, eighteen months after Alexander's monetary flood. Prices at market stalls have risen noticeably. A merchant adjusts the price board. Shoppers carry more coins to buy the same goods. Nobody knows why prices are higher. They just know bread costs more. Wide shot, Egyptian architectural elements, cinematic morning light."),
    ("AL13", "A Persian nobleman who had saved silver over decades, now sitting in his home counting his savings. The coins are there, but when he goes to the market, he finds they buy less than they used to. His wealth measured in coins has not changed. His purchasing power has. His expression carries a slowly dawning understanding. Cinematic medium portrait, Persian interior, lamplight."),
    ("AL14", "An ancient local economy in Asia Minor, circa 325 BCE. A village market that previously ran on grain-exchange and temple credit. Now flooded with Alexandrine coins. The local headman at the market looks confused and overwhelmed by the volume of unfamiliar currency flowing through. Traditional exchange systems disrupted by an external monetary injection nobody asked for. Cinematic wide shot."),
    ("AL15", "A Portuguese trading ship in the sixteenth century, anchored off the West African coast. Sailors lowering large nets full of cowrie shells over the side. The shells pour into waiting canoes. The scale is enormous — millions of shells offloaded in a single port visit. On the shore, local traders watch as their currency supply begins to change. Cinematic wide shot, tropical coastal setting."),
    ("AL16", "Close-up of cowrie shells pouring from a Portuguese trader's bag onto a West African market ground. They pile up among the shells already there, the pile growing dramatically larger. This is what monetary inflation looks like before anyone has a word for it. Hyperrealistic macro, tropical bright light, the shells sharp and white against dark earth."),
    ("AL17", "A West African elder, seated in front of his home, holding his lifetime savings in cowrie shells. He has hundreds. Three years ago, this was substantial wealth. Today, because of the Portuguese flooding the market, it buys less than half what it once did. His expression carries the quiet devastation of someone whose wealth has been made worthless by forces outside his control. Cinematic medium portrait, afternoon light."),
    ("AL18", "A Portuguese trading company ledger, circa 1640, open to a page showing the cost of cowrie shells from the Indian Ocean (very low) and the price received for them in West Africa (substantially higher). The profit from the currency arbitrage is documented. The mechanism of using monetary supply as a weapon is written in ordinary commercial language. Archival document style, candlelight."),
    ("AL19", "Alexander's empire map at its maximum extent, shown as a cinematic documentary visual. Gold lines show the paths of his minted coins radiating outward from the new mints at Persepolis, Ecbatana, and Susa. The coins travel faster than his armies. Within a decade of the conquest, the monetary system of the ancient world has been involuntarily Hellenized. Dark background, gold and red palette."),
    ("AL20", "A symbolic composition: two coins side by side. Left: a Persian daric (a pre-Alexander gold coin with the Persian king as archer). Right: an Alexander tetradrachm (Heracles on the obverse, Zeus on the reverse). The monetary sovereignty of Persia has been replaced by the monetary authority of Macedonia. Macro photography, dark background, museum lighting."),
    ("AL21", "A Black man narrator figure in a dark jacket standing before a large world map in a modern documentary setting. He gestures at West Africa and then at the Indian Ocean, tracing the Portuguese cowrie shell trade route. His expression is measured but pointed. The map behind him shows the centuries-long arc of monetary power used as a tool of extraction. Modern documentary aesthetic."),
    ("AL22", "Wide shot of a crowded West African coastal market in the sixteen hundreds — before the Portuguese cowrie flood. Orderly, prosperous, cowrie shells as currency in small, measured amounts. A functioning monetary economy on its own terms. Then the frame freezes — the moment before everything changes. Cinematic wide shot, tropical morning light, vibrant colors, period clothing."),
    ("AL23", "The same West African coastal market, one generation later. The cowrie piles everywhere are enormous. Prices are written in the hundreds where once they were in the dozens. Some stalls are closed. The economy is destabilized. The previous equilibrium is gone. No army came. Only ships with shells. Cinematic wide shot, same location, same light, different atmosphere."),
    ("AL24", "Close-up of a Macedonian silver tetradrachm bearing Alexander's posthumous portrait. The coin is beautifully struck, authoritative, the face of power. This coin circulated through economies from Greece to India, representing not just wealth but the imposition of a monetary standard. It is still being struck by successor kings thirty years after Alexander's death. Museum macro, dark background, raking light."),
    ("AL25", "Documentary comparison graphic: three historical instances of involuntary monetary flooding side by side. Left: Alexander releasing Persian bullion (330 BCE). Center: Portuguese flooding West African cowrie markets (1600s). Right: IMF structural adjustment loans imposing dollar dependence (1980s). Three cases, same mechanism, different packaging. Clean documentary graphic, dark background."),
    ("AL26", "A Black man narrator figure in a dark jacket seated at a simple table, looking directly at the camera. He holds a single coin. He says nothing. His expression carries the weight of everything the video has explained about what the coin is and has always been. Cinematic close portrait, neutral dark background, single key light. The narrator as human anchor for the argument."),
    ("AL27", "Wide establishing shot of Babylon under Alexander's rule, circa 323 BCE. The city is operating under Macedonian monetary governance. Local temple accounting systems are being replaced by coined-money transactions. Local merchants carry Alexander tetradrachms alongside their traditional weights and measures. The transition from local financial sovereignty to imperial currency is underway. Cinematic wide shot, ancient Mesopotamian architecture, golden light."),
    ("AL28", "A modern parallel to the cowrie flood: a documentary graphic showing the volume of U.S. dollar reserves flowing into a developing nation's economy through debt agreements, raising local prices and eroding local purchasing power. The mechanism is the same as Alexander's. Only the format has changed. Clean documentary infographic style, dark background."),
    ("AL29", "A West African scholar in the seventeen hundreds, writing about the cowrie inflation his community has experienced. He documents the price changes in a handwritten ledger. He understands what has happened even if he has no economic theory for it. His face shows the intelligence and frustration of someone documenting a harm they could not prevent. Candlelight, simple wooden desk, period West African clothing."),

    # ── ROME additional ──
    ("R08", "The Roman forum in the age of Augustus, circa 10 CE. Citizens conducting business. Merchants exchanging goods using bright silver denarii. The coins are new, consistent, trusted. A money-changer at a stone table tests the weight of coins on a balance. This is the high point of Roman monetary trust. Cinematic wide shot, midday sun, marble columns and white stone."),
    ("R09", "Nero's private mint in Rome, circa 64 CE. The emperor's orders have just arrived: reduce the silver content by ten percent, reduce the weight slightly. Mint officials study the new specifications. The die cutters adjust their work. Nobody outside this room knows yet. This is the first deliberate, order-driven debasement of the Roman currency system. Cinematic medium shot, torchlight, administrative atmosphere."),
    ("R10", "Close-up of a Nero-era denarius next to an Augustus-era denarius on dark stone. The difference in silver content is barely perceptible to the eye — the Nero coin is very slightly duller. But both coins say they are a denarius. Same denomination, different value. Macro photography, raking side light, museum quality."),
    ("R11", "A Roman provincial baker in the second century CE at his outdoor bread stall. He counts the coins he received that day — more in number than his father received for the same work, but some look different, slightly less silver. He frowns at a newer coin. He does not know why some coins look slightly different. But he will raise his prices next week. Cinematic medium shot, market light."),
    ("R12", "Septimius Severus in the Roman Senate, circa 195 CE, defending his monetary policies. He stands at the speaker's position in imperial purple, surrounded by senators in white togas. He is explaining why the denarius must be adjusted. The senators listen. None of them have the full picture of the cumulative debasement. The information asymmetry is complete. Cinematic wide shot, Roman Senate interior."),
    ("R13", "A visual sequence — three coins in a row on dark stone, separated by labeled markers. Left: Augustus denarius, gleaming silver. Center: Septimius Severus denarius, visibly more dull. Right: Gallienus antoninianus, clearly bronze with only a faint silver tinge. The labels read: YEAR 1 / YEAR 200 / YEAR 265. The debasement made visible as a timeline. Studio photography, dramatic lighting."),
    ("R14", "The Roman imperial mint in operation during the Crisis of the Third Century, circa 265 CE. Workers melting old silver-washed coins, adding more bronze, and re-striking them with new emperors' portraits. The process of incremental debasement made physical — the same metal, cycled again and again, with less silver each time. Cinematic wide shot, forge fire, industrial urgency."),
    ("R15", "A Roman legionnaire on campaign, late third century CE. He opens his pay pouch and counts the coins. They are lighter than last year's coins. He bites one and notices the bronze core. He looks at the coin for a long moment. He is beginning to understand something. But there is no word yet for what is happening to his money. Cinematic close-medium shot, military camp, firelight."),
    ("R16", "A Roman marketplace, circa 270 CE. A baker's price board shows the current price of bread. In the corner, a faded price board from twenty years ago, still readable. The old price was one-eighth of the current price. Both prices are in denarii. The coin called a denarius in both eras. They are not the same coin. Cinematic medium shot, market, warm light on the price boards."),
    ("R17", "A Roman soldier's petition — a clay tablet inscribed to the emperor requesting higher pay. The soldier has done the arithmetic as best he can. He knows his coins buy less. The petition is one of hundreds the emperor receives. Some are answered with coin increases. The increase comes in debased coins. The soldier calculates again. Cinematic close-up of the petition tablet, lamplight."),
    ("R18", "A map of the Roman Empire, circa 260 CE, showing the simultaneous pressures that define the Crisis of the Third Century. External barbarian pressures on multiple borders are marked. Internal political instability is shown as fracture lines. Economic stress zones are highlighted. The monetary collapse underlies all of it. Cinematic documentary map graphic, dark background, red and gold palette."),
    ("R19", "A Roman merchant's warehouse, late third century. He holds a sack of denarii he accepted in payment. He spreads them on a table — they look like a normal quantity of money. But when he goes to purchase goods from his supplier, they are worth less than he expected. He accepts this, as everyone is accepting it, because the alternative is not accepting any coins at all. Cinematic medium shot, warehouse, lamp light."),
    ("R20", "The Roman emperor Gallienus on his throne, circa 265 CE, receiving reports of the monetary crisis. Officials present him with data. His expression is the expression of a man managing a problem he did not create and cannot solve. The debasement was cumulative, the work of fifteen emperors before him. He is the one who will be blamed. Cinematic wide shot, imperial interior, torchlight."),
    ("R21", "A Roman empire supply chain in breakdown, circa 280 CE. Merchants refusing to accept debased coins for grain shipments to Rome. Officials threatening them with legal consequences. The merchant holds up the coin and points to the bronze showing through. The coin's authority is failing. What was once unthinkable — rejecting the emperor's coin — is now happening in provincial markets. Cinematic wide shot, tense atmosphere."),
    ("R22", "A fast-cut documentary sequence of coins: six Roman emperor portrait coins in succession, each slightly more bronze than the last, each stamped with a different emperor's face. They flash past like playing cards — Nero, Vespasian, Hadrian, Septimius Severus, Caracalla, Gallienus. The portrait changes. The silver drains away. Cinematic graphic sequence, dark background, macro coin photography."),
    ("R23", "The physical remnants of the Roman monetary system: an archaeological site where a hoard of third-century denarii was found, the coins corroded together into a lump because the bronze core oxidized. A modern archaeologist's hand holds the corroded mass up to the light. The coins that were designed to look silver are now visibly, undeniably bronze. Documentary photography, excavation setting."),
    ("R24", "A modern numismatist's table with Roman coins from different centuries displayed in a learning sequence. He points from a gleaming Augustus denarius to a corroded Gallienus antoninianus, explaining the debasement timeline to an off-camera student. The coins tell the story visually without words. Cinematic medium shot, modern setting, daylight through a window, coins on velvet."),
    ("R25", "Wide shot of Roman ruins at the height of the Crisis of the Third Century — a provincial city that was once prosperous, now showing signs of economic contraction. Empty market stalls. A fewer number of traders. Weeds growing in spaces that were once busy. The economic collapse expressed in urban landscape. Cinematic wide historical illustration, gray overcast light."),
    ("R26", "A Black man narrator figure in a dark jacket standing in front of the Roman Forum ruins in modern Rome — the actual ruins, recognizably the Forum. He looks at the columns and broken stone. He holds a Roman coin replica in his hand. Behind him, tourists walk through the ruins. He turns back to the camera. The ancient and modern coexist. Cinematic medium shot, Italian afternoon light."),
    ("R27", "A Roman family counting their household savings, late third century CE. A man, his wife, and adult children at a table with coin pouches. They count the coins. They have the same number as last year. They know it buys less. The youngest child asks why. The father has no answer that makes sense. The monetary debasement is invisible — it is not in the coins, it is in the relationship between the coins and reality. Cinematic medium shot, Roman domestic interior, lamplight."),
    ("R28", "Close-up of a soldier's hand holding two Roman coins of the same denomination side by side. Left coin: a Vespasian-era denarius, silver and solid. Right coin: a Gallienus-era antoninianus, bronze with silver traces. Both say they are worth the same. Both are stamped with imperial authority. One is worth three times the other in precious metal. This is the gap between the stamp and the substance. Cinematic macro, dramatic side light."),
    ("R29", "An abstract documentary graphic of the Roman monetary collapse timeline. A line graph showing the silver content of the denarius declining from 95 percent to 0.5 percent over 270 years. The line is smooth and relentless, with occasional brief stabilizations. At the bottom, the date range spans Augustus to Gallienus. The visual makes the systematic nature of the debasement undeniable. Clean documentary graphic, dark background."),
    ("R30", "Rome at night, circa 285 CE, viewed from the hills above the Tiber. The city is still vast, still lit by thousands of oil lamps. But it is quieter than it was a century ago. The monetary system that held the empire together is fraying. The physical city looks the same. What has changed is invisible. The trust that made the coins work is corroding, the same way the silver coating corrodes on the coins themselves. Wide cinematic establishing shot, night, distant city lights."),
    ("R31", "Final Rome image: the physical denarius coin in a museum curator's hand — a real surviving example from the late third century, bronze showing clearly through worn silver. The curator's white-gloved hand holds it carefully. The coin survived 1,750 years. The system it represented did not. Documentary photography, museum setting, precise lighting."),

    # ── MODERN additional ──
    ("M10", "Aerial view of Cerro Rico mountain in modern Potosi, Bolivia. The mountain is visibly hollowed out at the top from centuries of mining — you can see the excavation damage even from altitude. The colonial city of Potosi at its base is still there, still small by comparison to the mountain that defined it. The mountain changed the world's monetary system and it shows in the landscape. Cinematic aerial photography, cold high-altitude light."),
    ("M11", "The interior of the Casa de la Moneda, the Spanish royal mint in Potosi, as it exists today — now a museum. The massive wooden coin-pressing machines, powered by mules or human labor, still stand in the production hall. The scale is industrial, the machinery is brutal and simple. Tourists walk through. A Black man narrator figure, dressed in modern clothes, examines one of the machines with a grave expression. Cinematic museum photography, interior light."),
    ("M12", "A mita worker in colonial Potosi, circa 1600, descending into a mine shaft with a candle tied to his head. He is dressed in rough indigenous cloth, carrying a leather ore bag. The shaft entrance is stone, the darkness absolute beyond the candle's range. The mercury amalgamation process made the silver accessible; it also poisoned the workers. Cinematic medium shot, dramatic chiaroscuro."),
    ("M13", "The Spanish piece of eight — the real de a ocho — displayed as a macro photograph. The coin is large, roughly struck, with the Spanish royal arms on one face and the Pillars of Hercules on the other. Around the columns, the letters PTSI from the Potosi mint mark are visible. This is the coin that became the world's first global currency. Museum macro, dark background, raking light showing the coin's irregular handmade surface."),
    ("M14", "A period map of the Spanish empire's silver trade routes, circa 1600. Silver from Potosi flows by ship around Cape Horn to Spain, and by Manila Galleon across the Pacific to China. The routes are drawn as thick gold lines on a world map. This single mountain in Bolivia powered the world's first global monetary system. Cinematic documentary map, dark background, gold route lines."),
    ("M15", "A Chinese merchant in late Ming Dynasty Canton, circa 1590, receiving a large shipment of Spanish pieces of eight from a Manila Galleon trading mission. He weighs them and accepts them. China is demanding silver for silk and porcelain. The Spanish pieces of eight — minted in Potosi — have become the medium of exchange for the world's largest trade network. Cinematic medium wide shot, Chinese merchant dock, Ming-era clothing."),
    ("M16", "The United States Bureau of Engraving and Printing, modern era. A technician monitors a printing press as sheets of hundred-dollar bills emerge. The bills are counted by machine, stacked precisely. The cost of printing a hundred-dollar bill is less than seventeen cents. The government collects the rest. This is seigniorage in its modern form. Cinematic wide shot, industrial printing facility, documentary style."),
    ("M17", "A clean documentary graphic showing the seigniorage calculation: a hundred-dollar bill printed for seventeen cents. The gap between cost and face value is the government's profit. This gap traces directly to the Lydian mint's depletion gilding: the certified value exceeding the actual cost of the underlying material. Clean graphic on dark background, the numbers visible and clear."),
    ("M18", "A young person sitting at a kitchen table with student loan paperwork. She circles the clause that says the loan cannot be discharged in bankruptcy. She puts the pen down and looks at the clause. She reads it again. The moment of understanding what she has signed. Cinematic close-medium shot, apartment setting, morning light."),
    ("M19", "A documentary graphic showing student loan balance over time. A line starting at a hundred thousand dollars in 2010. Payments made faithfully each month — shown as small downward ticks on the line. But the line barely moves. Interest capitalizes. The principal barely decreases over ten years. The balance is still ninety thousand. The hektemoroi parallel visualized in modern data. Clean graphic, dark background."),
    ("M20", "Side-by-side comparison: left panel shows a horos stone in an ancient Attic field, recording a coin-denominated debt that grows regardless of the harvest. Right panel shows a modern student loan statement, a debt that grows regardless of the graduate's income. The obligation tracks the contract, not the reality. Same architecture, twenty-six centuries apart. Documentary comparison graphic."),
    ("M21", "The Royal Mint in Tower of London, circa 1700, Isaac Newton's era. The building exterior in period engraving style. Newton walks through the gate in a dark coat and wig, carrying papers. He is not here as a scientist today but as Master of the Mint, managing the Great Recoinage and investigating coin clippers. The scientist turned monetary official. Cinematic period illustration."),
    ("M22", "Isaac Newton in the interrogation of a coin clipper, circa 1698. Newton sits at a table across from a defendant in a plain wooden room. He examines a collection of clipped coins laid out on the table as evidence. His expression is focused, prosecutorial. As Master of the Mint, Newton personally supervised 28 executions for counterfeiting and clipping. His face shows the gravity of the work. Cinematic medium shot."),
    ("M23", "Macro close-up of a modern U.S. quarter held edge-on to the camera. The milled ridges are sharp and perfectly regular, extending all the way around the edge. Each ridge is Newton's invention, still reproduced on every coin today, three hundred years later. The ridges are both functional and historical — they are Newton's solution to clipping visible in every coin. Hyperrealistic macro, neutral background, raking light."),
    ("M24", "A modern phone screen showing a contactless payment app balance. The user has 847 dollars in a digital wallet. There are no coins. There is no metal. There is a number on a screen, certified by a financial authority, representing a claim on value that the issuing institution manages according to its own interests. The coin has been fully abstracted. Cinematic close-up, phone in hand, urban background blurred."),
    ("M25", "A Black man narrator figure in a modern dark jacket holding up a dollar bill to the camera. He turns it over slowly, examining both sides. Washington's portrait. The eagle. The Federal Reserve seal. The serial number. All the signifiers of certified authority. The same architecture as the lion's head stamp on the Lydian electrum stater. Cinematic medium shot, neutral dark background."),
    ("M26", "A documentary graphic showing the global monetary system as a network: central banks, commercial banks, digital payment processors, cryptocurrency exchanges. At the center: a certified number. Around it: layers of institutional authority. The network is vast and complex. At the core, the same architecture: a number, certified by an authority, backed by trust, adjustable at the authority's discretion. Clean network graphic, dark background."),
    ("M27", "A modern central bank trading floor — the Federal Reserve, the ECB, or similar. Screens showing currency exchange rates, bond yields, inflation data. Economists in business attire work at monitors. The modern version of the mint, managing the gap between face value and real value at civilizational scale. Cinematic wide shot, modern financial infrastructure."),
    ("M28", "Aristotle's Politics open to the relevant passage on money as a social convention, shown in a modern translation. The book is worn, marginalia in the margins. The passage reads: what money is, is what the community agrees it is, formalized by state authority. A hand highlights the relevant sentence. The argument that connects 330 BCE to the present in one page. Cinematic close-up, book on a modern desk, daylight."),
    ("M29", "A Black man narrator figure at a kitchen table with a collection of objects: a Lydian electrum stater replica, a Roman denarius, a Spanish piece of eight, and a modern dollar bill. All four side by side. He looks at all four. The same architecture across four monetary systems, separated by centuries. He touches each one. Cinematic medium shot, warm domestic light."),
    ("M30", "A wide shot of a modern city at dusk — New York, London, or Chicago. Office towers lit up, financial district visible. People walking in the streets below. The city runs on the same mechanism as the ancient Lydian market. The coin has disappeared. The logic runs everything in front of us. Cinematic wide establishing shot, blue-hour light, the modern monetary world at work."),
    ("M31", "A single modern coin — a U.S. quarter — dropped onto a dark stone surface in slow motion. It lands and spins, slows, and falls flat. The eagle side up. The milled edges catch the light as it spins. The coin is the end of a 2600-year chain of monetary innovation and deception. Cinematic slow-motion macro."),
    ("M32", "A museum display case showing the evolution of money in chronological order. From left to right: a clay token, a Lydian electrum stater, a Roman denarius, a Spanish piece of eight, an English pound note, a twentieth-century dollar bill, and a smartphone showing a digital wallet. The progression is clear. The architecture is identical throughout. Documentary museum photography, ambient display lighting."),
    ("M33", "Side-by-side documentary graphic: the Lydian mint's depletion gilding operation (73 percent gold surface, 54 percent gold core, lion stamp certifying face value) and the Federal Reserve's balance sheet showing assets and liabilities (money issued, cost of production, seigniorage profit). The structural parallel drawn explicitly. Two diagrams, same architecture, 2600 years apart."),
    ("M34", "A modern graduate, mid-twenties, standing outside a college campus building in cap and gown after graduation. He holds his diploma and his phone. On his phone: a student loan app showing his balance. He stands between the building that educated him and the debt that will follow him. His expression carries the awareness that comes after. Cinematic medium shot, campus background, morning light."),
    ("M35", "A Black man narrator figure in a dark jacket seated in a modern chair, looking directly at the camera. He is holding a copy of Aristotle's Politics in one hand. He looks at the camera with steady confidence. He has been through the whole argument. He is ready to leave the viewer with what they need to carry out. Cinematic close portrait, neutral background, single key light."),
    ("M36", "A time-lapse-style documentary graphic: the dollar sign evolving. Starting with the Potosi mint mark PTSI on the Spanish piece of eight. Then simplified to an S with two vertical lines. Then to the modern dollar sign. Three centuries of evolution from a Bolivian silver mountain to the symbol on every price tag in the United States. Clean graphic sequence, dark background."),
    ("M37", "The Pactolus River in modern Turkey — a small, ordinary-looking stream in the valley near modern Sart (ancient Sardis). Tourist signage visible at the bank. No gold in sight. A Black man narrator figure in modern clothing stands at the bank, looking at the water. The river that started the entire story is still there, completely unremarkable to look at. Cinematic medium shot, modern Turkey, afternoon light."),

    # ── CLOSING additional ──
    ("C06", "A Black man narrator figure in a dark jacket standing before a dark background, facing the camera directly, both hands at his sides. His expression is calm and final. He is about to deliver the closing statement. The simplicity of the image places the focus entirely on what he is about to say. Cinematic close portrait, single key light, the quiet before the last words."),
    ("C07", "A museum display of ancient coins from every civilization that invented coinage independently: Lydian electrum, Chinese bronze spade coins, Indian punch-marked coins, Greek silver owls, Roman denarii — all displayed in one illuminated case. Each civilization arrived at the same architecture: a certified number backed by authority. The universality of the design. Documentary museum photography, ambient display lighting."),
    ("C08", "Close-up of the Lydian electrum stater coin in its museum display, framed from a perspective that emphasizes the coin's small size. A single coin, three centimeters across, the beginning of three thousand years of monetary history. The scale of consequence relative to the scale of the object is the entire story. Macro photography, museum lighting, dark background."),
    ("C09", "The coin cross-section visual returns: the Lydian electrum stater sliced in half, gold surface / diluted core. This time, the visual is accompanied by a series of other cross-sections: the Roman denarius (silver surface / bronze core), the Spanish piece of eight (face value / extraction cost), a modern dollar bill (denomination printed / production cost). Each shows the same structure. Documentary graphic series."),
    ("C10", "A wide shot of a peaceful modern financial district — glass towers reflecting the sky, people going about ordinary business below. All of it running on the same architecture as a 2600-year-old Lydian workshop. The structure made invisible by the scale of normalization. The coin is gone. The logic built the skyline. Cinematic wide shot, midday business district light."),
    ("C11", "A single Lydian electrum stater coin on a dark surface. No hands, no people, just the coin. The lion's head stamp visible. The coin is 2600 years old and slightly worn. It is the origin of everything the video covered. We return to it at the end. Macro photography, museum-quality studio lighting, absolute dark background."),
    ("C12", "A Black man narrator figure in a dark jacket walking through a modern bank — marble floors, glass barriers, teller windows, ATM machines. He walks slowly through the center of the main hall, looking at it as if seeing it for the first time or the last time. The architecture of financial authority around him. Cinematic tracking shot, modern bank interior, institutional lighting."),
    ("C13", "A view from outside a large modern bank building — the Federal Reserve building in Washington, or the Bank of England in London. Wide establishing shot, the building imposing and classical. The same authority that the Lydian king expressed with a lion's head stamp is expressed here in neoclassical columns and marble. The architectural language of monetary legitimacy. Cinematic wide shot, gray-blue afternoon light."),
    ("C14", "The Pactolus River at full golden hour, water glinting. An extreme wide shot. The mountains behind are dramatic. The river is small in the landscape. The place where the coin was born is tiny relative to what it created. Cinematic ultra-wide shot, maximum golden hour light, the river as both origin and witness."),
    ("C15", "Documentary graphic: a timeline spanning three thousand years from the Lydian electrum stater to the present day. Key events marked along the line: Solon's seisachtheia, Alexander's Persian bullion, Roman debasement crisis, Potosi mint, Federal Reserve established, digital currency. The line is unbroken. The architecture is continuous. Clean graphic timeline, dark background, gold on dark."),
    ("C16", "Solon's horos stone — the original, historical artifact, in a museum case. A rectangular limestone slab with archaic Greek inscription. Small, weathered, profoundly significant. The physical evidence that the debt system existed, was canceled, and then returned. Documentary museum photography."),
    ("C17", "The closing image of the mint: the forge fire dying down at the end of the workday in the Lydian mint, circa 620 BCE. The workers have gone. The coins are bagged and gone. The fire embers glow. On the workbench, a single coin — the one that did not quite meet quality — left behind. The gap between surface and substance, present from the beginning. Cinematic wide shot of the empty workshop, ember light."),
    ("C18", "A modern hand placing a phone face-down on a table. The screen goes dark. No coins. No metal. No bank teller. No interface. Just a dark screen. And then a voice. The coin is gone. What remains is the relationship between a number and an authority. What remains is the same architecture as the first day. Cinematic close-up of the phone going dark, neutral background."),
    ("C19", "The Pactolus River at true dusk, nearly dark. The last light is gone. The water is black and still. The mountains are silhouettes. This is the final image of the video. The river that started everything is still there, unchanged after three thousand years of human monetary history. Cinematic wide, minimum light, contemplative, final."),
    ("C20", "A Black man narrator figure in a dark jacket, standing in a library or archive surrounded by shelves of books and ancient documents. He closes a very large book — a reference work on monetary history. He looks up at the camera. He has read the whole thing. So have we. His expression is neither hopeful nor despairing. It is clear. Cinematic medium portrait, library ambient light."),
    ("C21", "Final graphic: the Lydian electrum stater coin cross-section one last time. Gold surface, diluted core, lion stamp certifying a value the metal does not contain. The image is still. Under it, a single line of text: THREE THOUSAND YEARS. No additional explanation. The image and the timeline are the entire argument. Documentary graphic, maximum simplicity, dark background."),
    ("C22", "The Pactolus River aerial one final time — the same shot as H01 at the opening, but now at dusk instead of dawn. The symmetry is intentional. We began with the river. We end with the river. Everything in between happened in the gap between what the stamp said and what the metal contained. Cinematic aerial wide shot, dusk, the full circle."),

]

# ══════════════════════════════════════════════════════════
# GENERATION — No need to edit below this line
# ══════════════════════════════════════════════════════════

IMG_DIR = ROOT / f"projects/{PROJECT_NAME}/images"
IMG_DIR.mkdir(parents=True, exist_ok=True)


def generate_image(name, prompt, api_key):
    """Generate a single image using Gemini, with or without reference character."""
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=api_key)

    try:
        if USE_REF_IMAGE and REF_IMAGE_BYTES:
            contents = [
                types.Part.from_bytes(data=REF_IMAGE_BYTES, mime_type=REF_MIME),
                f"Using the attached image as a character reference, generate this scene in the EXACT same art style (Boondocks-style animation, bold linework, flat cel-shading). The character in every image must look like the man in the reference. Scene: {prompt}",
            ]
        else:
            contents = [f"Generate this scene: {prompt}"]

        response = client.models.generate_content(
            model=MODEL,
            contents=contents,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE", "TEXT"],
                temperature=0.7,
                image_config=types.ImageConfig(
                    image_size="4K",
                    aspect_ratio="16:9",
                ),
            ),
        )

        for part in response.candidates[0].content.parts:
            if part.inline_data is not None:
                img_data = part.inline_data.data
                mime = part.inline_data.mime_type
                ext = "png" if "png" in mime else "jpg"
                out_path = IMG_DIR / f"{name}.{ext}"
                if isinstance(img_data, str):
                    img_bytes = base64.b64decode(img_data)
                else:
                    img_bytes = img_data
                with open(out_path, "wb") as f:
                    f.write(img_bytes)
                cost = log_gemini_image_cost(IMG_DIR.parent, 1, name)
                print(f"  OK {name} → {out_path} ({len(img_bytes) // 1024} KB, cost: ${cost:.4f})")
                return name, str(out_path), ext
        return name, None, "No image in response"
    except Exception as e:
        print(f"  FAIL {name}: {e}")
        return name, None, str(e)


def main():
    remaining = []
    for name, prompt in IMAGES:
        if (IMG_DIR / f"{name}.png").exists() or (IMG_DIR / f"{name}.jpg").exists():
            print(f"  SKIP {name} (exists)")
        else:
            remaining.append((name, prompt))

    if not remaining:
        print("All images already generated!")
        return

    print(f"\nGenerating {len(remaining)} images using {MODEL}...\n")

    results = {}
    batch_size = len(API_KEYS)
    for batch_start in range(0, len(remaining), batch_size):
        batch = remaining[batch_start:batch_start + batch_size]
        if batch_start > 0:
            print(f"\n  -- Waiting 15s between batches to avoid rate limits --\n")
            time.sleep(15)

        with concurrent.futures.ThreadPoolExecutor(max_workers=len(batch)) as executor:
            futures = {}
            for i, (name, prompt) in enumerate(batch):
                key = API_KEYS[i % len(API_KEYS)]
                futures[executor.submit(generate_image, name, prompt, key)] = name

            for future in concurrent.futures.as_completed(futures):
                name, path, info = future.result()
                results[name] = (path, info)

    print(f"\n=== Summary ===")
    ok = sum(1 for p, _ in results.values() if p)
    print(f"  Generated: {ok}/{len(remaining)}")
    for name, (path, info) in sorted(results.items()):
        status = f"OK → {path}" if path else f"FAIL: {info}"
        print(f"  {name}: {status}")


if __name__ == "__main__":
    print(f"=== Generating images for project: {PROJECT_NAME} ===")
    main()
