#!/usr/bin/env python3
"""
generate_prompt_windows.py — Narration-per-window brief for image prompt writing.

Reads ElevenLabs character-level alignment files and prints the exact narration
text for each 10-second window. Use this BEFORE writing image prompts in W3b.
Each image prompt's narrative_context must match the words shown for its window.

Usage:
  python3 tools/generate_prompt_windows.py <project>
  python3 tools/generate_prompt_windows.py <project> <section_filter>

Examples:
  python3 tools/generate_prompt_windows.py war-dollar
  python3 tools/generate_prompt_windows.py war-dollar s2_bretton_woods
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WINDOW_SECONDS = 10.0


def get_text_in_window(chars, starts, start_s, end_s):
    return "".join(
        c for c, s in zip(chars, starts) if start_s <= s < end_s
    ).strip()


def process_file(json_path: Path):
    data = json.loads(json_path.read_text())
    chars  = data.get("characters", [])
    starts = data.get("character_start_times_seconds", [])
    ends   = data.get("character_end_times_seconds", [])

    if not chars or not ends:
        print(f"ERROR: {json_path.name} exists but contains no alignment data.")
        print("This clip's alignment is empty — re-run generate_audio.py for this section.")
        print("Do not write image prompts until all alignment files have data.")
        sys.exit(1)

    total = ends[-1]
    n_windows = int(total / WINDOW_SECONDS) + (1 if total % WINDOW_SECONDS else 0)

    print(f"  {json_path.stem}  ({total:.1f}s → {n_windows} windows @ {WINDOW_SECONDS:.0f}s each)")
    print()

    for i in range(n_windows):
        w_start = i * WINDOW_SECONDS
        w_end   = min(w_start + WINDOW_SECONDS, total)
        text    = get_text_in_window(chars, starts, w_start, w_end)
        label   = f"{int(w_start):3}s – {int(w_end):3}s"
        print(f"    {i+1:2}. [{label}]  {text}")

    print()


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 tools/generate_prompt_windows.py <project> [section_filter]")
        sys.exit(1)

    project = sys.argv[1]
    section_filter = sys.argv[2] if len(sys.argv) > 2 else None

    audio_dir = ROOT / f"projects/{project}/audio"
    if not audio_dir.exists():
        print(f"ERROR: audio directory not found: {audio_dir}")
        sys.exit(1)

    json_files = sorted(audio_dir.glob("*.json"))
    if not json_files:
        print(f"ERROR: No .json alignment files found in {audio_dir}")
        print("These are generated by generate_audio.py alongside each .mp3.")
        print("W3a must complete before W3b. Do not write prompts until alignment files exist.")
        sys.exit(1)

    # Check that every narration MP3 has a companion alignment JSON
    mp3_files = sorted([
        f for f in audio_dir.glob("*.mp3") if f.name != "music_bg.mp3"
    ])
    missing_json = [f for f in mp3_files if not (audio_dir / f"{f.stem}.json").exists()]
    if missing_json:
        print(f"ERROR: {len(missing_json)} MP3(s) are missing alignment JSON files:")
        for f in missing_json:
            print(f"  missing: {f.stem}.json")
        print("\nRe-run generate_audio.py for these clips before writing prompts.")
        print("Do not write image prompts until all alignment files are present.")
        sys.exit(1)

    matched = [f for f in json_files if not section_filter or section_filter in f.stem]
    if not matched:
        print(f"No files matching '{section_filter}' in {audio_dir}")
        sys.exit(1)

    print(f"\n{'='*70}")
    print(f"PROMPT WINDOWS — {project}  ({WINDOW_SECONDS:.0f}s per window)")
    print(f"Write one image prompt per window. narrative_context must match")
    print(f"the words shown for that window — not the section topic in general.")
    print(f"{'='*70}\n")

    for f in matched:
        process_file(f)


if __name__ == "__main__":
    main()
